.PHONY: all

CXX = g++

FLAGS = -Wall -O3 -D_USING_DEVICE_DNNL_ 

INC = -I../../install/include -I${DNNL_DIR}/include \

LINK = -L../../install/lib \
	   -L${DNNL_DIR}/lib \
	   -ltensortype -ldnnl 

all: repl 

repl: repl.cpp
	$(CXX) $(FLAGS) -o $@ $< $(INC) $(LINK)

clean:
	rm -f repl 
