.PHONY: all

FLAGS = -std=c++17 -Wall -O3 -D_USING_DEVICE_COREX_ -DUSING_DEVICE_DNNL_ 
INC = -I../../install/include -I${COREX_DIR}/include 
LINK = -L../../install/lib \
       -L${COREX_DIR}/lib \
	   -ltensortype -lcorex_kernels -lcudart -lcuda -lcublas

all: repl 

repl: repl.cpp
	g++ $(FLAGS) -o $@ $< $(INC) $(LINK)

run: repl 
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${COREX_DIR}/lib:${VT_SOURCE}/install/lib ./repl $(target) 

clean:
	rm -f repl 
