.PHONY: all

CXX = /home/teaonly/opt/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android32-clang++

FLAGS = -Wall -fopenmp -O3 -D_USING_DEVICE_ACL_ 

INC = -I../../install/include -I${ACL_DIR} -I${ACL_DIR}/include

LINK = -L../../install/lib \
	   -L${ACL_DIR}/lib/arm64-v8.2-a-neon/ \
	   -L/home/teaonly/opt/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/32 \
	   -ltensortype -larm_compute

all: repl 

repl: repl.cpp
	$(CXX) $(FLAGS) -o $@ $< $(INC) $(LINK)

clean:
	rm -f repl 
