.PHONY: all

FLAGS = -Wall -fopenmp -O3 -D_USING_DEVICE_DNNL_ 
INC = -I../../install/include -I${DNNL_DIR}/include 

LINK = -L../../install/lib \
	   -L${DNNL_DIR}/lib \
	   -L/usr/lib/x86_64-linux-gnu \
	   -ltokenizer_combo -ltokenizers_c \
	   -ltensortype -ldnnl

all: chat

chat: chat.cpp memory.hpp
	g++ $(FLAGS) -o $@ $< $(INC) $(LINK)

run16: chat 
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${DNNL_DIR}/lib:${VT_SOURCE}/install/lib ./chat ./inference_fp16.dag

clean:
	rm -f chat bech 
